preferences for kde
Donnnno/Arcticons-Linux pull request #22
Opened 2023-11-21 19:32 UTC by Donnnno

2023-12-18 21:08 UTC, Donnnno commented
forgot I stared making this, I think these are ready to merge tho

2023-12-19 15:56 UTC, autinerd requested changes

2023-12-19 15:56 UTC, autinerd commented on mapping.yaml
> +  - preferences/
These lines should be removed.

2023-12-19 21:09 UTC, Donnnno commented on mapping.yaml
> +  - preferences/
Oops 🙃

2023-12-21 18:39 UTC, autinerd approved these changes

2023-12-21 18:41 UTC, merged